INSERT OR IGNORE INTO products (name, slug, description, price, category, stock, is_active, featured, created_at) VALUES
('Art Mens Shirt', 'art-mens-shirt', 'Authentic Pacific Island fashion.', 4500, 'shirts', 24, 1, 0, datetime('now')),
('Tribal Mask Mens Shirt', 'tribal-mask-mens-shirt', 'Authentic Pacific Island fashion.', 4500, 'shirts', 24, 1, 0, datetime('now')),
('Summer Break Mens Shirt', 'summer-break-mens-shirt', 'Authentic Pacific Island fashion.', 4500, 'shirts', 18, 1, 0, datetime('now')),
('Mens Shirt Tribal', 'mens-shirt-tribal', 'Authentic Pacific Island fashion.', 3500, 'shirts', 18, 1, 0, datetime('now')),
('Mens Shirt Tapa', 'mens-shirt-tapa', 'Authentic Pacific Island fashion.', 3500, 'shirts', 12, 1, 0, datetime('now')),
('Summer Break Ladies Dress', 'summer-break-ladies-dress', 'Authentic Pacific Island fashion.', 4500, 'dresses', 14, 1, 0, datetime('now')),
('Tribal Mask Ladies Top', 'tribal-mask-ladies-top', 'Authentic Pacific Island fashion.', 4000, 'dresses', 14, 1, 0, datetime('now')),
('Art Ladies Dress', 'art-ladies-dress', 'Authentic Pacific Island fashion.', 4500, 'dresses', 14, 1, 0, datetime('now')),
('Art Boys Shirt', 'art-boys-shirt', 'Authentic Pacific Island fashion.', 3000, 'kids', 12, 1, 0, datetime('now')),
('Art Girls Dress', 'art-girls-dress', 'Authentic Pacific Island fashion.', 3000, 'kids', 12, 1, 0, datetime('now')),
('Ladies Top Tapa', 'ladies-top-tapa', 'Authentic Pacific Island fashion.', 3500, 'dresses', 7, 1, 0, datetime('now')),
('Ladies Top Tribal', 'ladies-top-tribal', 'Authentic Pacific Island fashion.', 3500, 'dresses', 6, 1, 0, datetime('now')),
('Wild Banana Mens Shirt', 'wild-banana-mens-shirt', 'Authentic Pacific Island fashion.', 4500, 'shirts', 6, 1, 0, datetime('now')),
('Boys Shirt Tapa', 'boys-shirt-tapa', 'Authentic Pacific Island fashion.', 3000, 'kids', 6, 1, 0, datetime('now')),
('Girls Dress Tapa', 'girls-dress-tapa', 'Authentic Pacific Island fashion.', 3000, 'kids', 6, 1, 0, datetime('now')),
('Wild Banana Boys Shirt', 'wild-banana-boys-shirt', 'Authentic Pacific Island fashion.', 3000, 'kids', 6, 1, 0, datetime('now')),
('Wild Banana Girls Dress', 'wild-banana-girls-dress', 'Authentic Pacific Island fashion.', 3000, 'kids', 6, 1, 0, datetime('now')),
('Mens Shirt Nature', 'mens-shirt-nature', 'Authentic Pacific Island fashion.', 4500, 'shirts', 12, 1, 0, datetime('now')),
('Mens Shirt Tribal Hibiscus', 'mens-shirt-tribal-hibiscus', 'Authentic Pacific Island fashion.', 3500, 'shirts', 12, 1, 0, datetime('now')),
('Mens Shirt Tribal Mana', 'mens-shirt-tribal-mana', 'Authentic Pacific Island fashion.', 3500, 'shirts', 12, 1, 0, datetime('now')),
('Mens Shirt Tribal Mat', 'mens-shirt-tribal-mat', 'Authentic Pacific Island fashion.', 3500, 'shirts', 12, 1, 0, datetime('now')),
('CANOE CLUB MENS SHIRT', 'canoe-club-mens-shirt', 'Authentic Pacific Island fashion.', 4000, 'shirts', 10, 1, 0, datetime('now')),
('Wild Banana Ladies Top', 'wild-banana-ladies-top', 'Authentic Pacific Island fashion.', 4000, 'dresses', 7, 1, 0, datetime('now')),
('Ladies Top Tribal Hibiscus', 'ladies-top-tribal-hibiscus', 'Authentic Pacific Island fashion.', 3500, 'dresses', 7, 1, 0, datetime('now')),
('Ladies Top Tribal Mana', 'ladies-top-tribal-mana', 'Authentic Pacific Island fashion.', 3500, 'dresses', 6, 1, 0, datetime('now')),
('Ladies Top Tribal Mat', 'ladies-top-tribal-mat', 'Authentic Pacific Island fashion.', 3500, 'dresses', 6, 1, 0, datetime('now'));
